### ISSUE TITLE
incorrect release description for 2.2.0

### ISSUE THREAD

**Issue by rrrafalsz** [spatie/laravel-sluggable#126]
the release description for 2.2.0 states that support for PHP 7.2 was dropped. in fact, it was 7.1. please update this as it might cause users some confusion (as it did for me) and they might even end up not updating the package.

**Comment by freekmurze** [comment]
Fixed.

**Comment by rrrafalsz** [comment]
@freekmurze i still see the same description [on the release page](https://github.com/spatie/laravel-sluggable/releases/tag/2.2.0).

**Comment by freekmurze** [comment]
Now changed on the release notes too.
